// Bundles the Functions source into dist/ for the emulator and for deploy.
//
// Why a bundle: `firebase deploy` uploads the functions directory and runs
// `npm install` in the cloud, which cannot resolve pnpm `workspace:*`
// dependencies. esbuild inlines @serviceflow/* (and zod), and we generate a
// dist/package.json listing only the real runtime dependencies.
import { build } from "esbuild";
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outdir = resolve(root, "dist");
const pkg = JSON.parse(await readFile(resolve(root, "package.json"), "utf8"));

// Provided by the Cloud Functions runtime via npm install — never bundled.
const RUNTIME_DEPENDENCIES = ["firebase-admin", "firebase-functions"];

// Clean dist's contents rather than the directory itself: a running Functions
// emulator holds dist/ open (EBUSY on Windows) and keeps its own resolved
// params in dist/.env.local, which we leave alone.
await mkdir(outdir, { recursive: true });
for (const entry of await readdir(outdir)) {
  if (entry !== ".env.local") await rm(resolve(outdir, entry), { recursive: true, force: true });
}

await build({
  entryPoints: [resolve(root, "src/index.ts")],
  outfile: resolve(outdir, "index.js"),
  bundle: true,
  platform: "node",
  target: "node22",
  format: "cjs",
  sourcemap: true,
  external: RUNTIME_DEPENDENCIES.flatMap((d) => [d, `${d}/*`]),
  logLevel: "info",
});

const deployPkg = {
  name: "serviceflow-functions",
  private: true,
  description: "Generated by apps/functions/scripts/build.mjs — do not edit.",
  main: "index.js",
  // Cloud Functions runtime (firebase.json also pins nodejs22).
  engines: { node: "22" },
  dependencies: Object.fromEntries(RUNTIME_DEPENDENCIES.map((d) => [d, pkg.dependencies[d]])),
};
await writeFile(resolve(outdir, "package.json"), `${JSON.stringify(deployPkg, null, 2)}\n`);
console.log(`Wrote ${outdir}/package.json`);

// Firebase reads params from .env files in the functions source dir (dist/).
// Copy local, non-secret param files across; .env.example is documentation only.
for (const file of await readdir(root)) {
  if (/^\.env(\.[\w-]+)?$/.test(file) && file !== ".env.example") {
    await copyFile(resolve(root, file), resolve(outdir, file));
    console.log(`Copied ${file} -> dist/${file}`);
  }
}
